name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger condition: v0.15.2, v1.0.0, etc.

permissions:
  contents: write
  id-token: write  # For OIDC trusted publishing

jobs:
  # Job 1: Build Python Package
  build-python:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*

  # Job 2: Publish to PyPI (using OIDC trusted publishing)
  publish-pypi:
    name: Publish to PyPI
    needs: build-python
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jupyter-nbmodel-client
    permissions:
      id-token: write  # Required for OIDC
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No password needed, using OIDC trusted publishing
          skip-existing: true